id: ID876B6C2
legacy_id: P000635
ocr_import_info:
  bdrc_scan_id: W23630
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T14:13:46'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T01:23:53.582510+00:00'
last_modified: 2022-09-02 09:25:22.971080
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W23630
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW23630
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བླ་མ་དམ་པ་བསོད་ནམས་རྒྱལ་མཚན་གྱི་བཀའ་འབུམ་ལས་པོད་ད་པ།
  author: བླ་མ་དམ་པ་བསོད་ནམས་རྒྱལ་མཚན།
statistics:
  ocr_word_mean_confidence_index: 0.9092860600054268
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I3543:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3543
      total_pages: 1146
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3543.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9092860600054268
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
