id: P000635
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W23630
  title: བླ་མ་དམ་པ་བསོད་ནམས་རྒྱལ་མཚན་གྱི་བཀའ་འབུམ་ལས་པོད་ད་པ།
  author: ''
  volumes:
    bafc5eb522fa41f4bc7fc2bdba42648b:
      image_group_id: I3543
      title: ''
      volume_number: 1
      total_pages: 1146
      base_file: v001.txt
